function Gl = Gl_matrix_fun(CW1_1,CW1_2,CW1_3,CW1_4,CW2_1,CW2_2,CW2_3,CW2_4,d_w,delta1,delta2,delta3,delta4,rW1_1,rW1_2,rW1_3,rW1_4,rW2_1,rW2_2,rW2_3,rW2_4,s_w)
%GL_MATRIX_FUN
%    GL = GL_MATRIX_FUN(CW1_1,CW1_2,CW1_3,CW1_4,CW2_1,CW2_2,CW2_3,CW2_4,D_W,DELTA1,DELTA2,DELTA3,DELTA4,RW1_1,RW1_2,RW1_3,RW1_4,RW2_1,RW2_2,RW2_3,RW2_4,S_W)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    17-Jan-2018 15:15:13

t2 = 1.0./s_w;
t3 = cos(delta1);
t4 = sin(delta1);
t5 = cos(delta2);
t6 = sin(delta2);
t7 = cos(delta3);
t8 = sin(delta3);
t9 = cos(delta4);
t10 = sin(delta4);
t11 = 1.0./rW1_1;
t12 = CW1_1.*t3;
t13 = CW2_1.*t4;
t14 = t12+t13;
t15 = d_w.*t2.*t4.*(1.0./2.0);
t16 = 1.0./rW2_1;
t17 = CW2_1.*t3;
t18 = d_w.*t2.*t14.*(1.0./2.0);
t19 = 1.0./rW1_2;
t20 = CW1_2.*t5;
t21 = CW2_2.*t6;
t22 = t20+t21;
t23 = d_w.*t2.*t6.*(1.0./2.0);
t24 = 1.0./rW2_2;
t25 = CW2_2.*t5;
t26 = d_w.*t2.*t22.*(1.0./2.0);
t27 = 1.0./rW1_3;
t28 = CW1_3.*t7;
t29 = CW2_3.*t8;
t30 = t28+t29;
t31 = d_w.*t2.*t8.*(1.0./2.0);
t32 = 1.0./rW2_3;
t33 = CW2_3.*t7;
t34 = d_w.*t2.*t30.*(1.0./2.0);
t35 = 1.0./rW1_4;
t36 = CW1_4.*t9;
t37 = CW2_4.*t10;
t38 = t36+t37;
t39 = d_w.*t2.*t10.*(1.0./2.0);
t40 = 1.0./rW2_4;
t41 = CW2_4.*t9;
t42 = d_w.*t2.*t38.*(1.0./2.0);
Gl = reshape([1.0,0.0,0.0,-t2.*t4,-t2.*t6,-t2.*t8,-t2.*t10,t11.*(t3+t15),t16.*(t3-t15),t19.*(t5+t23),t24.*(t5-t23),t27.*(t7+t31),t32.*(t7-t31),t35.*(t9+t39),t40.*(t9-t39),0.0,1.0,0.0,t2.*t3,t2.*t5,t2.*t7,t2.*t9,t11.*(t4-d_w.*t2.*t3.*(1.0./2.0)),t16.*(t4+d_w.*t2.*t3.*(1.0./2.0)),t19.*(t6-d_w.*t2.*t5.*(1.0./2.0)),t24.*(t6+d_w.*t2.*t5.*(1.0./2.0)),t27.*(t8-d_w.*t2.*t7.*(1.0./2.0)),t32.*(t8+d_w.*t2.*t7.*(1.0./2.0)),t35.*(t10-d_w.*t2.*t9.*(1.0./2.0)),t40.*(t10+d_w.*t2.*t9.*(1.0./2.0)),0.0,0.0,1.0,t2.*t14-1.0,t2.*t22-1.0,t2.*t30-1.0,t2.*t38-1.0,-t11.*(t17+t18-CW1_1.*t4),t16.*(-t17+t18+CW1_1.*t4),-t19.*(t25+t26-CW1_2.*t6),t24.*(-t25+t26+CW1_2.*t6),-t27.*(t33+t34-CW1_3.*t8),t32.*(-t33+t34+CW1_3.*t8),-t35.*(t41+t42-CW1_4.*t10),t40.*(-t41+t42+CW1_4.*t10)],[15,3]);
